name:                nop
version:             0.1.0.0
github:              "githubuser/nop"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nop#readme>

dependencies:
- base >= 4.7 && < 5
- text ^>= 1.2 
- lens ^>= 5.1
- vector ^>= 0.12
- bytestring ^>= 0.11 
- containers ^>= 0.6.5
- unordered-containers ^>= 0.2.18
- aeson ^>= 2.0
- parsec >= 3 && < 4
- http-client ^>= 0.7 
- http-client-tls ^>= 0.3 
- http-types ^>= 0.12 
- time >= 1.9 && < 2
- directory ^>= 1.3
- Chart ^>= 1.9
- Chart-diagrams ^>= 1.9
- Chart-cairo ^>= 1.9
- regex-pcre-builtin >= 0.95 && < 0.96

# - gnuplot >= 0.5.7 && < 0.6
# - regex-tdfa ^>= 1.3
# - conduit ^>= 1.3
# - reddit >= 0.2 && < 0.4
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  nop-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nop

tests:
  nop-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nop
